name: payments-service-ci

on:
  pull_request:
    branches: [develop]
    paths:
      - apps/payments-service/**
      - gitops/environments/dev/payments-service-values.yaml
  push:
    branches: [develop]
    paths:
      - apps/payments-service/**
      - gitops/environments/dev/payments-service-values.yaml

permissions:
  contents: write
  pull-requests: write
  id-token: write
  security-events: write
  attestations: write
  packages: write

jobs:
  pipeline:
    uses: steinshei/platform-cicd/.github/workflows/reusable-ci.yml@v1.9
    with:
      service_name: payments-service
      context_dir: apps/payments-service
      dockerfile: apps/payments-service/Dockerfile
      run_tests: true
    secrets: inherit

  update-dev-gitops:
    needs: [pipeline]
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'deploy(dev):')
    uses: steinshei/platform-cicd/.github/workflows/reusable-gitops-dev-update.yml@v1.9
    with:
      service_name: payments-service
      values_file: gitops/environments/dev/payments-service-values.yaml
      image_tag: ${{ github.sha }}
      skip_if_deploy_commit: true
    secrets:
      ci_bot_token: ${{ secrets.CI_BOT_TOKEN }}
