name: platform-ci-poc

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: Service name
        required: true
        default: sample-service
      context_dir:
        description: Build context directory
        required: true
        default: apps/sample-service
      dockerfile:
        description: Dockerfile path
        required: true
        default: apps/sample-service/Dockerfile
      run_tests:
        description: Run unit tests
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write
  security-events: write
  attestations: write
  packages: write

jobs:
  ci-via-platform-reusable-workflow:
    # PoC: call reusable workflow via repository reference.
    # In production multi-repo setup, replace repo/ref with org platform repo and version tag.
    uses: steinshei/cicd-platform-blueprint/.github/workflows/reusable-ci.yml@main
    with:
      service_name: ${{ inputs.service_name }}
      context_dir: ${{ inputs.context_dir }}
      dockerfile: ${{ inputs.dockerfile }}
      run_tests: ${{ inputs.run_tests }}
    secrets: inherit
