# 该工作流用于在 pull request 和 push 到 main 分支时运行安全静态应用程序安全测试（SAST），使用 CodeQL 和 Semgrep 进行代码分析和漏洞检测。
name: security-sast

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: go
            build-mode: none
          - language: actions
            build-mode: none
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      - name: Autobuild
        if: matrix.build-mode == 'autobuild'
        uses: github/codeql-action/autobuild@v3
        # 执行分析并上传结果
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
